create table
  public.potions (
    id integer generated by default as identity,
    potion_type integer[] not null,
    sku text null,
    inventory integer null,
    cost integer null,
    potion_name text null,
    constraint potions_pkey primary key (id),
    constraint potions_inventory_check check ((inventory >= 0))
  ) tablespace pg_default;

  create table
  public.carts (
    id integer generated by default as identity,
    constraint carts_pkey primary key (id),
    constraint carts_id_key unique (id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    cart_id integer generated by default as identity,
    potion_id integer not null,
    quantity integer null,
    constraint cart_items_pkey primary key (cart_id, potion_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potions (id)
  ) tablespace pg_default;

  create table
  public.transactions_orders (
    id integer generated by default as identity,
    potion_id integer null,
    gold_change integer null default 0,
    potion_change integer null default 0,
    cart_id integer null,
    time timestamp with time zone null,
    barrel_id integer null,
    ml_change integer null default 0,
    constraint transactions_pkey primary key (id),
    constraint transactions_orders_barrel_id_fkey foreign key (barrel_id) references ml_types (id),
    constraint transactions_orders_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint transactions_orders_potion_id_fkey foreign key (potion_id) references potions (id)
  ) tablespace pg_default;

  create table
  public.ml_types (
    id integer generated by default as identity,
    types character varying null,
    constraint ml_types_pkey primary key (id)
  ) tablespace pg_default;